lang: en
timezone: Australia/Brisbane
title: Unpacked
tagline: notes on malware, phishing & reverse engineering and other cyber crime
description: >-
  Hands-on malware analysis, phishing teardowns, and reverse engineering.
url: "https://opsectester.github.io"
baseurl: ""
github:
  username: Opsectester
social:
  name: Opsectester
  email: opsectester@gmail.com
  links:
    - https://github.com/Opsectester
